const root=document.documentElement;const button=document.querySelector('.theme-button');const label=document.querySelector('.theme-label');const modes=['auto','light','dark'];let mode=localStorage.getItem('portfolio-theme')||'auto';function applyTheme(){if(mode==='auto')root.removeAttribute('data-theme');else root.dataset.theme=mode;label.textContent=mode[0].toUpperCase()+mode.slice(1);button.title=`Theme: ${mode}`}applyTheme();button.addEventListener('click',()=>{mode=modes[(modes.indexOf(mode)+1)%modes.length];localStorage.setItem('portfolio-theme',mode);applyTheme()});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.style.transitionDelay=`${entry.target.dataset.delay||0}ms`;entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const glow=document.querySelector('.cursor-glow');window.addEventListener('pointermove',e=>{glow.style.left=`${e.clientX}px`;glow.style.top=`${e.clientY}px`},{passive:true});document.querySelector('#year').textContent=new Date().getFullYear();

document.querySelectorAll('.skill-filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.skill-filter').forEach(item=>item.classList.remove('active'));button.classList.add('active');const filter=button.dataset.filter;document.querySelectorAll('.capability-card').forEach(card=>{const show=filter==='all'||card.dataset.category===filter;card.classList.toggle('filtered-out',!show)})}));

document.querySelector('#contact-form')?.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const subject=encodeURIComponent(data.get('subject'));const body=encodeURIComponent(`Hi Dheeraj,\n\n${data.get('message')}\n\nBest,\n${data.get('name')}\n${data.get('email')}`);window.location.href=`mailto:dheerajarjula@gmail.com?subject=${subject}&body=${body}`});

const roles=['Full-Stack Developer','Applied AI Engineer','Machine Learning Engineer','Data Engineer','Data Analyst','Data Scientist','Software Engineer'];const roleElement=document.querySelector('#dynamic-role');let roleIndex=0;if(roleElement&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){setInterval(()=>{roleElement.classList.add('role-exit');setTimeout(()=>{roleIndex=(roleIndex+1)%roles.length;roleElement.textContent=roles[roleIndex];roleElement.classList.remove('role-exit');roleElement.classList.add('role-enter');requestAnimationFrame(()=>requestAnimationFrame(()=>roleElement.classList.remove('role-enter')))},380)},2500)}
